# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."nextcloud-aio-mastercontainer" = {
    image = "ghcr.io/nextcloud-releases/all-in-one:latest";
    volumes = [
      "/nextcloud_aio_mastercontainer:/mnt/docker-aio-config:rw"
      "/var/run/docker.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "80:80/tcp"
      "8080:8080/tcp"
      "8443:8443/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=nextcloud-aio-mastercontainer"
      "--network=nextcloud-aio_default"
    ];
  };
  systemd.services."podman-nextcloud-aio-mastercontainer" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-nextcloud-aio_default.service"
    ];
    requires = [
      "podman-network-nextcloud-aio_default.service"
    ];
    partOf = [
      "podman-compose-nextcloud-aio-root.target"
    ];
    wantedBy = [
      "podman-compose-nextcloud-aio-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-nextcloud-aio_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f nextcloud-aio_default";
    };
    script = ''
      podman network inspect nextcloud-aio_default || podman network create nextcloud-aio_default
    '';
    partOf = [ "podman-compose-nextcloud-aio-root.target" ];
    wantedBy = [ "podman-compose-nextcloud-aio-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-nextcloud-aio-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
