# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  virtualisation = {
    oci-containers.backend = "docker";
    docker = {
      enable = true;
      autoPrune.enable = true;
    };
  };

  # Containers
  virtualisation.oci-containers.containers = {
    nextcloud = {
      image = "ghcr.io/nextcloud-releases/all-in-one:latest";
      volumes = [
        "/nextcloud_aio_mastercontainer:/mnt/docker-aio-config:rw"
        "/var/run/docker.sock:/var/run/docker.sock:ro"
      ];
      ports = [
        "80:80/tcp"
        "8080:8080/tcp"
        "8443:8443/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--network-alias=nextcloud-aio-mastercontainer"
        "--network=nextcloud-aio_default"
      ];
    };
  };
}
